# Generated by Django 6.0.3 on 2026-08-22 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=200, verbose_name='Bot Token')),
                ('channel_id', models.CharField(blank=True, max_length=100, verbose_name='Kanal ID')),
                ('channel_username', models.CharField(blank=True, max_length=100, verbose_name='Kanal Username (@...)')),
                ('welcome_message', models.TextField(blank=True, default="🌿 Quva Nihol Marketplacega Xush Kelibsiz!\n\nBu yerda ko'chat va meva-sabzavot sotish mumkin.", verbose_name='Xush kelibsiz xabari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bot faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Sozlamalari',
                'verbose_name_plural': 'Bot Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kochat', "🌱 Ko'chat"), ('meva', '🍎 Meva/Mahsulot')], max_length=20, verbose_name='Mahsulot turi')),
                ('name', models.CharField(max_length=200, verbose_name='Turi/Nomi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Soni (dona)')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name="Yoshi (ko'chat uchun)")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('location_text', models.CharField(blank=True, max_length=300, verbose_name='Manzil matni')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram foydalanuvchi ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('telegram_full_name', models.CharField(blank=True, max_length=200, verbose_name='Telegram ism')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Rasm')),
                ('telegram_file_id', models.CharField(blank=True, max_length=200, verbose_name='Telegram file ID')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
    ]
