# Generated by Django 6.0.3 on 2026-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='product',
            name='standardized_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Standart nomi (To'g'rilangan)"),
        ),
    ]
