# Generated by Django 6.0.3 on 2026-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_district_product_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='channel_url',
            field=models.URLField(blank=True, verbose_name='Kanal havolasi (Ssilkasi)'),
        ),
    ]
