# Generated by Django 6.0.3 on 2026-08-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_botsettings_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=50, verbose_name="Jinsi (Erkak/Urg'ochi)"),
        ),
        migrations.AddField(
            model_name='product',
            name='milk_yield',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sut berishi (litrda)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name="Og'irligi/Massasi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kochat', "🌱 Ko'chat"), ('meva', '🍎 Meva/Mahsulot'), ('chorva', '🐄 Chorva'), ('parranda', '🐔 Parranda'), ('tuxum', '🥚 Tuxum')], max_length=20, verbose_name='Mahsulot turi'),
        ),
    ]
