# Generated by Django 6.0.3 on 2026-08-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_gender_product_milk_yield_product_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kochat', "🌱 Ko'chat"), ('meva', '🍎 Meva/Mahsulot'), ('sabzavot', '🥕 Sabzavot'), ('parranda', '🐔 Parranda'), ('tuxum', '🥚 Tuxum')], max_length=20, verbose_name='Mahsulot turi'),
        ),
    ]
