# Generated by Django 6.0.3 on 2026-08-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(max_length=100, verbose_name='Daraxt turi')),
                ('tree_count', models.IntegerField(verbose_name='Daraxt soni')),
                ('tree_age', models.IntegerField(verbose_name='Daraxt yoshi (yil)')),
                ('bearing_age', models.IntegerField(verbose_name='Meva berish yoshi (yil)')),
                ('ready_month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name="Meva tayyor bo'lish oyi")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('location_text', models.CharField(blank=True, max_length=300, verbose_name='Manzil matni')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_full_name', models.CharField(blank=True, max_length=200)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bog' yozuvi",
                'verbose_name_plural': "Bog' yozuvlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='welcome_message',
            field=models.TextField(blank=True, default="🛒 24/7 Savdo Marketplacega Xush Kelibsiz!\n\nBu yerda ko'chat, meva-sabzavot va boshqa qishloq xo'jaligi mahsulotlarini sotish mumkin.", verbose_name='Xush kelibsiz xabari'),
        ),
    ]
