# Generated by Django 6.0.3 on 2026-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_orchardrecord_alter_botsettings_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Sotilganmi?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sotilgan sana'),
        ),
    ]
