# Generated by Django 6.0.3 on 2026-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_product_is_sold_product_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Miqdori (matn)'),
        ),
    ]
