# Conversation states
(
    CHOOSING_CATEGORY,
    
    # Kochat
    KOCHAT_NAME,
    KOCHAT_AGE,
    KOCHAT_PRICE,
    KOCHAT_QUANTITY,
    KOCHAT_PHOTOS,
    KOCHAT_LOCATION,
    KOCHAT_PHONE,
    KOCHAT_DESCRIPTION,
    
    # Meva
    MEVA_NAME,
    MEVA_PRICE,
    MEVA_QUANTITY,
    MEVA_PHOTOS,
    MEVA_LOCATION,
    MEVA_PHONE,
    MEVA_DESCRIPTION,
    
    # Sabzavot
    SABZAVOT_NAME,
    SABZAVOT_PRICE,
    SABZAVOT_QUANTITY,
    SABZAVOT_PHOTOS,
    SABZAVOT_LOCATION,
    SABZAVOT_PHONE,
    SABZAVOT_DESCRIPTION,
    
    # Parranda Choice (Parranda or Tuxum)
    PARRANDA_CHOICE,
    
    # Parranda
    PARRANDA_TYPE,
    PARRANDA_QUANTITY,
    PARRANDA_WEIGHT,
    PARRANDA_DESCRIPTION,
    PARRANDA_LOCATION,
    PARRANDA_PHONE,
    PARRANDA_PRICE,
    PARRANDA_PHOTOS,
    
    # Tuxum
    TUXUM_TYPE,
    TUXUM_QUANTITY,
    TUXUM_DESCRIPTION,
    TUXUM_LOCATION,
    TUXUM_PHONE,
    TUXUM_PRICE,
    TUXUM_PHOTOS,

    CONFIRM,

    # Daraxt / Bog'
    DARAXT_TYPE,
    DARAXT_COUNT,
    DARAXT_AGE,
    DARAXT_BEARING_AGE,
    DARAXT_READY_MONTH,
    DARAXT_LOCATION,
    DARAXT_PHONE,
    DARAXT_DESCRIPTION,

) = range(48)
